# Generated by Django 5.2.7 on 2025-10-17 18:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del niño/a', max_length=200, verbose_name='Nombre Completo')),
                ('edad', models.IntegerField(help_text='Edad del niño/a en años', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_ninos/', verbose_name='Foto del Niño/a')),
                ('nombre_responsable', models.CharField(max_length=200, verbose_name='Nombre del Responsable')),
                ('telefono_responsable', models.CharField(max_length=20, verbose_name='Teléfono del Responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Responsable')),
                ('parentesco', models.CharField(help_text='Ej: Madre, Padre, Tutor, etc.', max_length=50, verbose_name='Parentesco')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura (cm)')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, help_text='Describir todas las alergias conocidas', verbose_name='Alergias')),
                ('enfermedades', models.TextField(blank=True, help_text='Enfermedades crónicas o condiciones médicas', verbose_name='Enfermedades')),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos que toma regularmente', verbose_name='Medicamentos')),
                ('observaciones_medicas', models.TextField(blank=True, verbose_name='Observaciones Médicas')),
                ('documento_medico', models.FileField(blank=True, help_text='Recetas, certificados médicos, etc.', null=True, upload_to='documentos_medicos/', verbose_name='Documento Médico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el niño/a está actualmente en la guardería', verbose_name='Activo')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
