# Generated by Django 5.2.7 on 2025-10-21 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(help_text='Documento de identidad', max_length=50, verbose_name='Número de Identificación (DUI, Pasaporte, etc.)')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('relacion', models.CharField(help_text='Ej: Tío, Abuelo, Hermano mayor, Amigo de la familia', max_length=100, verbose_name='Relación con el Niño')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa del responsable', verbose_name='Dirección')),
                ('foto', models.ImageField(blank=True, help_text='Foto para identificación', null=True, upload_to='fotos_responsables/', verbose_name='Fotografía del Responsable')),
                ('fecha_inicio_autorizacion', models.DateField(verbose_name='Fecha de Inicio de Autorización')),
                ('fecha_fin_autorizacion', models.DateField(blank=True, help_text='Dejar en blanco si es autorización permanente', null=True, verbose_name='Fecha de Fin de Autorización')),
                ('dias_autorizados', models.CharField(blank=True, help_text='Ej: L,M,X,J,V (Lunes a Viernes)', max_length=50, verbose_name='Días Autorizados')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora desde la cual puede retirar al niño', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora hasta la cual puede retirar al niño', null=True, verbose_name='Hora de Fin')),
                ('firma_electronica', models.TextField(blank=True, help_text='Firma digital en formato base64', verbose_name='Firma Electrónica')),
                ('observaciones', models.TextField(blank=True, help_text='Información adicional o restricciones', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la autorización está vigente', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables_autorizados', to='core.nino', verbose_name='Niño')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Responsable Autorizado',
                'verbose_name_plural': 'Responsables Autorizados',
                'ordering': ['-activo', 'nombre_completo'],
            },
        ),
    ]
