# Generated by Django 5.2.7 on 2025-10-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aula_maestro_seccion_horarioaula_asignacionaula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='usuario',
        ),
    ]
