# Generated by Django 5.2.7 on 2025-10-24 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_maestro_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True, verbose_name='¿Asistió?')),
                ('motivo_inasistencia', models.TextField(blank=True, help_text='Obligatorio si el niño no asistió', null=True, verbose_name='Motivo de inasistencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.nino')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('nino', 'fecha')},
            },
        ),
    ]
