# Generated by Django 5.2.7 on 2025-10-29 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medico', 'Médico'), ('familiar', 'Familiar'), ('personal', 'Personal')], max_length=20, verbose_name='Tipo de Permiso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si es ausencia de un solo día', null=True, verbose_name='Fecha de Fin')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Opcional: para ausencias parciales', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Opcional: para ausencias parciales', null=True, verbose_name='Hora de Fin')),
                ('motivo', models.TextField(help_text='Describa brevemente el motivo del permiso', verbose_name='Motivo de la Ausencia')),
                ('documento', models.FileField(blank=True, help_text='Adjunte certificado médico, carta, etc. (opcional)', null=True, upload_to='permisos_ausencia/%Y/%m/', verbose_name='Documento de Comprobante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas_gestion', models.TextField(blank=True, help_text='Comentarios del administrador', verbose_name='Notas de Gestión')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_gestion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Gestión')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Gestionado por')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_ausencia', to='core.nino', verbose_name='Niño')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Permiso de Ausencia',
                'verbose_name_plural': 'Permisos de Ausencia',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
