# Generated by Django 5.2.7 on 2025-11-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_permisoausencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadreNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='core.nino', verbose_name='Niño')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Padre/Tutor')),
            ],
            options={
                'verbose_name': 'Relación Padre-Niño',
                'verbose_name_plural': 'Relaciones Padre-Niño',
                'unique_together': {('padre', 'nino')},
            },
        ),
    ]
